// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0G-lxlX7ulTDfVyyALs5lSOkgl4qjl60',
    appId: '1:375349131641:web:146b00c6a82ffaed0257a8',
    messagingSenderId: '375349131641',
    projectId: 'alpha16-3e2e4',
    authDomain: 'alpha16-3e2e4.firebaseapp.com',
    storageBucket: 'alpha16-3e2e4.firebasestorage.app',
    measurementId: 'G-J35YNCKJLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf05ElWMDsgRgMGfkkWqWvw7pUmPVVm7U',
    appId: '1:375349131641:android:d9e8bcb149b0342b0257a8',
    messagingSenderId: '375349131641',
    projectId: 'alpha16-3e2e4',
    storageBucket: 'alpha16-3e2e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTPqsEXRRJPwIkeZSSA31NIxHgm_nGSA0',
    appId: '1:375349131641:ios:86cb3d1b7cc54af60257a8',
    messagingSenderId: '375349131641',
    projectId: 'alpha16-3e2e4',
    storageBucket: 'alpha16-3e2e4.firebasestorage.app',
    iosBundleId: 'com.example.alpha16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTPqsEXRRJPwIkeZSSA31NIxHgm_nGSA0',
    appId: '1:375349131641:ios:86cb3d1b7cc54af60257a8',
    messagingSenderId: '375349131641',
    projectId: 'alpha16-3e2e4',
    storageBucket: 'alpha16-3e2e4.firebasestorage.app',
    iosBundleId: 'com.example.alpha16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0G-lxlX7ulTDfVyyALs5lSOkgl4qjl60',
    appId: '1:375349131641:web:5293c55240c0734f0257a8',
    messagingSenderId: '375349131641',
    projectId: 'alpha16-3e2e4',
    authDomain: 'alpha16-3e2e4.firebaseapp.com',
    storageBucket: 'alpha16-3e2e4.firebasestorage.app',
    measurementId: 'G-Y8HCF5VSVG',
  );
}
